[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs", "npm install && npm run prod"]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
