providers = ["php"]

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = ["npm run prod"]

[start]
cmd = "php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
